language: r
sudo: required

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: iUbodhwdTWY/Lu+u0THafzSCMB+5im7XCYEAoIxNB61KSD0i99e+reqKXy2c5Rh8XS4KqlhOZ7FN0ivJ9T0DU1sIN27cyIZJHwDL3sY2tKsPlrxATM07+WVuVhvHVeF8JGktbI/mHspoI1OSzAoPZsj7LUdWyDIGYNGwYNXqt04=
