language: r
sudo: false
cache: packages
dist: trusty

r_packages:
  - covr

matrix:
  include:
    - r: oldrel
    - r: release
      env: R_CODECOV=true
    - r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

after_success:
- if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: iUbodhwdTWY/Lu+u0THafzSCMB+5im7XCYEAoIxNB61KSD0i99e+reqKXy2c5Rh8XS4KqlhOZ7FN0ivJ9T0DU1sIN27cyIZJHwDL3sY2tKsPlrxATM07+WVuVhvHVeF8JGktbI/mHspoI1OSzAoPZsj7LUdWyDIGYNGwYNXqt04=
